### ISSUE TITLE
Adding pre-configured components to a form without launching the edit modal

### ISSUE THREAD

**Issue by AbdallaMohamed** [formio/ngFormBuilder#227]
Recently, we made a PR, introducing the `lockConfiguration` property that allows registering components that have their configuration locked so the edit modal wouldn't be opened when they're dragged into a form.

The problem that we're facing now is that these components aren't getting a unique key anymore. Since the modal doesn't open. The directive `form-builder-option-key` doesn't get executed, and it's that directive that contains the `uniquify` function that gives the components its unique key.

Is there any solution or workaround to this problem?

**Comment by andreiho** [comment]
@travist @randallknutson Any comment on this one? This is a really important feature for us, we'd be willing to fix it ourselves but we'd first like to get your opinion on it.

**Comment by andreiho** [comment]
Another use case is containers pre-configured with components. We have custom container components that are registered with one or more default components attached. When dragging these containers in the form, the components added to the container do not get unique keys, because we're not showing the configuration modal for them. Is there any supported way to achieve this, or is it a feature request?

**Comment by andreiho** [comment]
In short, it should be possible to configure any component to be added to the form as it is, without editing it first. This should generate the unique key, trigger the `formUpdate` event and still allow later editing as you would normally do, via the "edit" button. If the component is a container, panel or similar, and it contains a list of child components added to it programatically, all child components should go through the same process.
