### ISSUE TITLE
Uniquify

### ISSUE THREAD

**Issue by basile-laderchi** [formio/ngFormBuilder#276]
After the uniquify function has been put in the BuilderUtils factory it doesn't exactly work.

Steps to reproduce:
1) create 2 new textfield without inputting any label.
2) edit the 2nd created control and change the property name from textfield2 to textfield and click save.
3) the id of the field is kept as textfield which is not the way it worked before.

**Comment by zackurben** [comment]
@basile-laderchi thanks for the report, this is however expected. We decoupled the uniquification process from the edit modal itself, which had its share of quirks.

Now if you manually change a key to be a duplicate, rather than programmatically changing on you, we force the user to select what value they want.

We are however working to resolve an issue with only the first instance of a duplicate key being highlighted in red, in the form builder.
