### ISSUE TITLE
How to add a new tab

### ISSUE THREAD

**Issue by Kolanravinder** [formio/ngFormBuilder#288]
Hi Team,

I am new to formio, I have a requirement to add a new tab to the "Layout Components" section.
for eg: After adding a textbox to the formio, a popup model is being populated with few tabs. I want to add a new custom tab for that model popup.
It would be great if any one can sha
![mytab](https://cloud.githubusercontent.com/assets/28542957/25857355/d0b6cff8-34a6-11e7-922e-64d5d0d99550.png)
re their experience.
for reference please find the enclosed screenshot.

Regards
Raveendar Reddy Kolan

**Comment by KRGLV** [comment]
Please Provide Solution for same. Same Requirement i have.

**Comment by travist** [comment]
This is doable with the latest form builder interface found @ https://github.com/formio/formio.js. This is our latest form builder library and we recommend using that instead of this library. The docs for adding/removing tabs can be found @ http://formio.github.io/formio.js/app/examples/custombuilder.html
