### ISSUE TITLE
How to set a unique key for a custom component that doesn't change according to label?  

### ISSUE THREAD

**Issue by Morshed0308** [formio/ngFormBuilder#441]
Hello I want the **key** property of JSON schema to be a unique key which doesn't change on label name ,How I can I do that?

For example 

```
"components": [
        {
            "label": "Text Field",
            "allowMultipleMasks": false,
            "showWordCount": false,
            "showCharCount": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "textfield",
            "input": true,
            **"key": "Mycustomkey",**
            "defaultValue": "",
}
```

I want to keep this **key** name no matter what I put on label name on this component. 

@travist  @randallknutson

**Comment by randallknutson** [comment]
In the newer versions of our form builder (in formio.js) the key is not modified for any existing components. It is only generated when the component is first added to the form. You may want to try updating to the latest beta version of ngFormio (which now includes the builder instead of being in a separate module) and see how it works.

**Comment by Morshed0308** [comment]
Okay,thanks ! I will try that ! but in the old version is there any way I can set the **key** specific and it doesn't change on label name?
@randallknutson

**Comment by wag110894** [comment]
You can change the API key in the API tab of each component.  It is labeled "Property Name". This will not change the label name of the component.

Hope this helps.

Thanks.
